### PR TITLE
Update nix.vim

### PR DESCRIPTION
**Pull request by SRGOM**
I removed the custom formatting- it's never included in file type plugins. Seeing as yours is a super popular plugin, I figured you wouldn't mind me changing this. Thanks.

### CODE REVIEW

**Comment by LnL7** [comment]
I'm not sure what the problem is, it's the indentation from the [nix styleguide](https://nixos.org/nixpkgs/manual/#sec-syntax). And it's pretty common for lanuage plugins to set this by default, it's not global.

> Use 2 spaces of indentation per indentation level in Nix expressions, 4 spaces in shell scripts.

- https://github.com/vim/vim/blob/4ca41534b726c4116d2e430e877e34146b4d4831/runtime/ftplugin/python.vim#L118
- https://github.com/vim/vim/blob/4ca41534b726c4116d2e430e877e34146b4d4831/runtime/ftplugin/ruby.vim#L142
- https://github.com/elixir-editors/vim-elixir/blob/98c03047d15dfa62cedf56e27bffb03772d41753/ftplugin/elixir.vim#L18

**Comment by SRGOM** [comment]
Thanks for considering my pull request. Would you be open to me adding the `g:nix_recommended_style` `if` check around the expand tab code?

You're right about Nix recommending it, of course.

**Comment by LnL7** [comment]
Yeah, I don't understand the usecase but adding an option to disable it would be fine.

**Comment by SRGOM** [comment]
Thanks, let me know what you think.

**Comment by SRGOM** [comment]
Thank you, I've made the recommended changes. Please let me know if there is anything else needed.

**Comment by LnL7** [comment]
That's perfect, Thanks!

**Comment by SRGOM** [comment]
Thank you for the review.

**Comment by asymmetric** [comment]
AFAIU, this is not set by default to 1, right? So the recommended style is opt-in, correct?

**Pull request merged**
